// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pypumvmonwppalisehcj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB5cHVtdm1vbndwcGFsaXNlaGNqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyNzQyNjIsImV4cCI6MjA2ODg1MDI2Mn0.E4VCSh7aW0x7Jm0TNzI0LNVrA63j3zUyDm-PjGZXGE4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});